In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# Reading the raw data given to us

In [3]:
#test = pd.read_csv('./test.csv')

In [4]:
#test

In [5]:
#test.describe()

In [6]:
data = pd.read_csv('./train.csv')

In [7]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,LP002911,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,LP002912,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
589,LP002926,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
590,LP002928,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban,Y
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
592,LP002933,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
593,LP002936,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,Y
594,LP002938,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
598,LP002945,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
604,LP002959,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
data.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [9]:
print('\n\nColumn Names\n\n')
print(data.columns)

Column Names


Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [10]:
#label encode the target variable
encode = LabelEncoder()
data.Loan_Status = encode.fit_transform(data.Loan_Status)

# drop the null values
data.dropna(how='any',inplace=True)

In [67]:
data['Loan_Status']

1      0
2      1
3      1
4      1
5      1
6      1
7      0
8      1
9      0
10     1
12     1
13     0
14     1
15     1
17     0
18     0
20     0
21     1
22     0
25     1
26     1
27     1
28     0
31     0
32     0
33     1
34     0
37     1
38     1
39     1
      ..
575    1
577    1
578    1
580    1
581    0
582    1
584    0
585    0
586    1
587    1
589    0
590    1
591    0
593    1
594    1
595    1
596    0
598    1
599    1
602    1
603    1
604    1
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 480, dtype: int64

In [68]:
# train-test-split   
X_train, X_test, y_train, y_test = train_test_split(data,data['Loan_Status'],test_size=0.2,random_state=0)

In [69]:
X_train

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
481,LP002536,Male,Yes,3+,Not Graduate,No,3095,0.0,113.0,360.0,1.0,Rural,1
341,LP002116,Female,No,0,Graduate,No,2378,0.0,46.0,360.0,1.0,Rural,0
297,LP001954,Female,Yes,1,Graduate,No,4666,0.0,135.0,360.0,1.0,Urban,1
255,LP001846,Female,No,3+,Graduate,No,3083,0.0,255.0,360.0,1.0,Rural,1
271,LP001891,Male,Yes,0,Graduate,No,11146,0.0,136.0,360.0,1.0,Urban,1
359,LP002160,Male,Yes,3+,Graduate,No,5167,3167.0,200.0,360.0,1.0,Semiurban,1
74,LP001253,Male,Yes,3+,Graduate,Yes,5266,1774.0,187.0,360.0,1.0,Semiurban,1
384,LP002236,Male,Yes,2,Graduate,No,4566,0.0,100.0,360.0,1.0,Urban,0
484,LP002543,Male,Yes,2,Graduate,No,8333,0.0,246.0,360.0,1.0,Semiurban,1
574,LP002863,Male,Yes,3+,Graduate,No,6406,0.0,150.0,360.0,1.0,Semiurban,0
486,LP002545,Male,No,2,Graduate,No,3547,0.0,80.0,360.0,0.0,Rural,0
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,1
82,LP001267,Female,Yes,2,Graduate,No,1378,1881.0,167.0,360.0,1.0,Urban,0
312,LP002006,Female,No,0,Graduate,No,2507,0.0,56.0,360.0,1.0,Rural,1
58,LP001198,Male,Yes,1,Graduate,No,8080,2250.0,180.0,360.0,1.0,Urban,1
196,LP001666,Male,No,0,Graduate,No,8333,3750.0,187.0,360.0,1.0,Rural,1
69,LP001241,Female,No,0,Graduate,No,4300,0.0,136.0,360.0,0.0,Semiurban,0
224,LP001750,Male,Yes,0,Graduate,No,6250,0.0,128.0,360.0,1.0,Semiurban,1
217,LP001726,Male,Yes,0,Graduate,No,3727,1775.0,131.0,360.0,1.0,Semiurban,1
593,LP002936,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,1
253,LP001843,Male,Yes,1,Not Graduate,No,2661,7101.0,279.0,180.0,1.0,Semiurban,1
200,LP001674,Male,Yes,1,Not Graduate,No,2600,2500.0,90.0,360.0,1.0,Semiurban,1
280,LP001910,Male,No,1,Not Graduate,Yes,4053,2426.0,158.0,360.0,0.0,Urban,0
575,LP002868,Male,Yes,2,Graduate,No,3159,461.0,108.0,84.0,1.0,Urban,1
566,LP002836,Male,No,0,Graduate,No,3333,0.0,70.0,360.0,1.0,Urban,1
557,LP002795,Male,Yes,3+,Graduate,Yes,10139,0.0,260.0,360.0,1.0,Semiurban,1
510,LP002637,Male,No,0,Not Graduate,No,3598,1287.0,100.0,360.0,1.0,Rural,0
205,LP001692,Female,No,0,Not Graduate,No,4408,0.0,120.0,360.0,1.0,Semiurban,1
203,LP001688,Male,Yes,1,Not Graduate,No,3500,1083.0,135.0,360.0,1.0,Urban,1
62,LP001207,Male,Yes,0,Not Graduate,Yes,2609,3449.0,165.0,180.0,0.0,Rural,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,LP002683,Male,No,0,Graduate,No,4683,1915.0,185.0,360.0,1.0,Semiurban,0
342,LP002119,Male,Yes,1,Not Graduate,No,4554,1229.0,158.0,360.0,1.0,Urban,1
91,LP001318,Male,Yes,2,Graduate,No,6250,5654.0,188.0,180.0,1.0,Semiurban,1
426,LP002367,Female,No,1,Not Graduate,No,4606,0.0,81.0,360.0,1.0,Rural,0
33,LP001098,Male,Yes,0,Graduate,No,3500,1667.0,114.0,360.0,1.0,Semiurban,1
211,LP001711,Male,Yes,3+,Graduate,No,3430,1250.0,128.0,360.0,0.0,Semiurban,0
430,LP002377,Female,No,1,Graduate,Yes,8624,0.0,150.0,360.0,1.0,Semiurban,1
594,LP002938,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,1
222,LP001744,Male,No,0,Graduate,No,2971,2791.0,144.0,360.0,1.0,Semiurban,1
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,0
52,LP001164,Female,No,0,Graduate,No,4230,0.0,112.0,360.0,1.0,Semiurban,0
248,LP001824,Male,Yes,1,Graduate,No,2882,1843.0,123.0,480.0,1.0,Semiurban,1
404,LP002301,Female,No,0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural,0
509,LP002634,Female,No,1,Graduate,No,13262,0.0,40.0,360.0,1.0,Urban,1
116,LP001404,Female,Yes,0,Graduate,No,3167,2283.0,154.0,360.0,1.0,Semiurban,1
89,LP001310,Male,Yes,0,Graduate,No,5695,4167.0,175.0,360.0,1.0,Semiurban,1
115,LP001401,Male,Yes,1,Graduate,No,14583,0.0,185.0,180.0,1.0,Rural,1
376,LP002219,Male,Yes,3+,Graduate,No,8750,4996.0,130.0,360.0,1.0,Rural,1
306,LP001993,Female,No,0,Graduate,No,3762,1666.0,135.0,360.0,1.0,Rural,1
358,LP002158,Male,Yes,0,Not Graduate,No,3000,1666.0,100.0,480.0,0.0,Urban,0
269,LP001884,Female,No,1,Graduate,No,2876,1560.0,90.0,360.0,1.0,Urban,1
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,1
459,LP002473,Male,Yes,0,Graduate,No,8334,0.0,160.0,360.0,1.0,Semiurban,0
250,LP001835,Male,Yes,0,Not Graduate,No,1668,3890.0,201.0,360.0,0.0,Semiurban,0
320,LP002051,Male,Yes,0,Graduate,No,2400,2167.0,115.0,360.0,1.0,Semiurban,1
414,LP002335,Female,Yes,0,Not Graduate,No,2149,3237.0,178.0,360.0,0.0,Semiurban,0
247,LP001819,Male,Yes,1,Not Graduate,No,6608,0.0,137.0,180.0,1.0,Urban,1
152,LP001531,Male,No,0,Graduate,No,9166,0.0,244.0,360.0,1.0,Urban,0
60,LP001205,Male,Yes,0,Graduate,No,2500,3796.0,120.0,360.0,1.0,Urban,1
220,LP001736,Male,Yes,0,Graduate,No,2221,0.0,60.0,360.0,0.0,Urban,0

In [70]:
X_test

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,0
161,LP001562,Male,Yes,0,Graduate,No,7933,0.0,275.0,360.0,1.0,Urban,0
182,LP001636,Male,Yes,0,Graduate,No,4600,0.0,73.0,180.0,1.0,Semiurban,1
340,LP002115,Male,Yes,3+,Not Graduate,No,2647,1587.0,173.0,360.0,1.0,Rural,0
216,LP001722,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural,0
183,LP001637,Male,Yes,1,Graduate,No,33846,0.0,260.0,360.0,1.0,Semiurban,0
512,LP002643,Male,Yes,2,Graduate,No,3283,2035.0,148.0,360.0,1.0,Urban,1
549,LP002777,Male,Yes,0,Graduate,No,2785,2016.0,110.0,360.0,1.0,Rural,1
148,LP001519,Female,No,0,Graduate,No,10000,1666.0,225.0,360.0,1.0,Rural,0
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,1
440,LP002408,Male,No,0,Graduate,No,3660,5064.0,187.0,360.0,1.0,Semiurban,1
153,LP001532,Male,Yes,2,Not Graduate,No,2281,0.0,113.0,360.0,1.0,Rural,0
564,LP002832,Male,Yes,2,Graduate,No,8799,0.0,258.0,360.0,0.0,Urban,0
418,LP002345,Male,Yes,0,Graduate,No,1025,2773.0,112.0,360.0,1.0,Rural,1
319,LP002050,Male,Yes,1,Graduate,Yes,10000,0.0,155.0,360.0,1.0,Rural,0
285,LP001924,Male,No,0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural,1
94,LP001325,Male,No,0,Not Graduate,No,3620,0.0,25.0,120.0,1.0,Semiurban,1
137,LP001491,Male,Yes,2,Graduate,Yes,3316,3500.0,88.0,360.0,1.0,Urban,1
400,LP002288,Male,Yes,2,Not Graduate,No,2889,0.0,45.0,180.0,0.0,Urban,0
455,LP002455,Male,Yes,2,Graduate,No,3859,0.0,96.0,360.0,1.0,Semiurban,1
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,1
135,LP001488,Male,Yes,3+,Graduate,No,4000,7750.0,290.0,360.0,1.0,Semiurban,0
310,LP002002,Female,No,0,Graduate,No,2917,0.0,84.0,360.0,1.0,Semiurban,1
50,LP001155,Female,Yes,0,Not Graduate,No,1928,1644.0,100.0,360.0,1.0,Semiurban,1
500,LP002603,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural,1
409,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,0
277,LP001904,Male,Yes,0,Graduate,No,3103,1300.0,80.0,360.0,1.0,Urban,1
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,1
558,LP002798,Male,Yes,0,Graduate,No,3887,2669.0,162.0,360.0,1.0,Semiurban,1
445,LP002429,Male,Yes,1,Graduate,Yes,3466,1210.0,130.0,360.0,1.0,Rural,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,LP002296,Male,No,0,Not Graduate,No,2755,0.0,65.0,300.0,1.0,Rural,0
96,LP001327,Female,Yes,0,Graduate,No,2484,2302.0,137.0,360.0,1.0,Semiurban,1
520,LP002689,Male,Yes,2,Not Graduate,No,2192,1742.0,45.0,360.0,1.0,Semiurban,1
424,LP002364,Male,Yes,0,Graduate,No,14880,0.0,96.0,360.0,1.0,Semiurban,1
185,LP001640,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,1
68,LP001238,Male,Yes,3+,Not Graduate,Yes,7100,0.0,125.0,60.0,1.0,Urban,1
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,1
291,LP001938,Male,Yes,2,Graduate,No,4400,0.0,127.0,360.0,0.0,Semiurban,0
311,LP002004,Male,No,0,Not Graduate,No,2927,2405.0,111.0,360.0,1.0,Semiurban,1
386,LP002239,Male,No,0,Not Graduate,No,2346,1600.0,132.0,360.0,1.0,Semiurban,1
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,1
70,LP001243,Male,Yes,0,Graduate,No,3208,3066.0,172.0,360.0,1.0,Urban,1
210,LP001708,Female,No,0,Graduate,No,10000,0.0,214.0,360.0,1.0,Semiurban,0
75,LP001255,Male,No,0,Graduate,No,3750,0.0,113.0,480.0,1.0,Urban,0
241,LP001800,Male,Yes,1,Not Graduate,No,2510,1983.0,140.0,180.0,1.0,Urban,0
90,LP001316,Male,Yes,0,Graduate,No,2958,2900.0,131.0,360.0,1.0,Semiurban,1
474,LP002524,Male,No,2,Graduate,No,5532,4648.0,162.0,360.0,1.0,Rural,1
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,0
119,LP001422,Female,No,0,Graduate,No,10408,0.0,259.0,360.0,1.0,Urban,1
519,LP002684,Female,No,0,Not Graduate,No,3400,0.0,95.0,360.0,1.0,Rural,0
300,LP001964,Male,Yes,0,Not Graduate,No,1800,2934.0,93.0,360.0,0.0,Urban,0
362,LP002175,Male,Yes,0,Graduate,No,4750,2333.0,130.0,360.0,1.0,Urban,1
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,1
464,LP002493,Male,No,0,Graduate,No,4166,0.0,98.0,360.0,0.0,Semiurban,0
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,0
532,LP002723,Male,No,2,Graduate,No,3588,0.0,110.0,360.0,0.0,Rural,0
534,LP002731,Female,No,0,Not Graduate,Yes,18165,0.0,125.0,360.0,1.0,Urban,1
142,LP001504,Male,No,0,Graduate,Yes,6950,0.0,175.0,180.0,1.0,Semiurban,1
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,0
243,LP001807,Male,Yes,2,Graduate,Yes,6250,1300.0,108.0,360.0,1.0,Rural,1

In [71]:
y_train

481    1
341    0
297    1
255    1
271    1
359    1
74     1
384    0
484    1
574    0
486    0
595    1
82     0
312    1
58     1
196    1
69     0
224    1
217    1
593    1
253    1
200    1
280    0
575    1
566    1
557    1
510    0
205    1
203    1
62     0
      ..
518    0
342    1
91     1
426    0
33     1
211    0
430    1
594    1
222    1
596    0
52     0
248    1
404    0
509    1
116    1
89     1
115    1
376    1
306    1
358    0
269    1
10     1
459    0
250    0
320    1
414    0
247    1
152    0
60     1
220    0
Name: Loan_Status, Length: 384, dtype: int64

In [72]:
y_test

18     0
161    0
182    1
340    0
216    0
183    0
512    1
549    1
148    0
27     1
440    1
153    0
564    0
418    1
319    0
285    1
94     1
137    1
400    0
455    1
599    1
135    0
310    1
50     1
500    1
409    0
277    1
610    1
558    1
445    1
      ..
401    0
96     1
520    1
424    1
185    1
68     1
607    1
291    0
311    1
386    1
606    1
70     1
210    0
75     0
241    0
90     1
474    1
7      0
119    1
519    0
300    0
362    1
8      1
464    0
9      0
532    0
534    1
142    1
591    0
243    1
Name: Loan_Status, Length: 96, dtype: int64

In [76]:

# seperate the target and independent variable
X_train = X_train.drop(['Loan_ID','Loan_Status'],axis=1)
X_test = X_test.drop(['Loan_ID','Loan_Status'],axis=1)

In [77]:
X_train

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
481,Male,Yes,3+,Not Graduate,No,3095,0.0,113.0,360.0,1.0,Rural
341,Female,No,0,Graduate,No,2378,0.0,46.0,360.0,1.0,Rural
297,Female,Yes,1,Graduate,No,4666,0.0,135.0,360.0,1.0,Urban
255,Female,No,3+,Graduate,No,3083,0.0,255.0,360.0,1.0,Rural
271,Male,Yes,0,Graduate,No,11146,0.0,136.0,360.0,1.0,Urban
359,Male,Yes,3+,Graduate,No,5167,3167.0,200.0,360.0,1.0,Semiurban
74,Male,Yes,3+,Graduate,Yes,5266,1774.0,187.0,360.0,1.0,Semiurban
384,Male,Yes,2,Graduate,No,4566,0.0,100.0,360.0,1.0,Urban
484,Male,Yes,2,Graduate,No,8333,0.0,246.0,360.0,1.0,Semiurban
574,Male,Yes,3+,Graduate,No,6406,0.0,150.0,360.0,1.0,Semiurban
486,Male,No,2,Graduate,No,3547,0.0,80.0,360.0,0.0,Rural
595,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural
82,Female,Yes,2,Graduate,No,1378,1881.0,167.0,360.0,1.0,Urban
312,Female,No,0,Graduate,No,2507,0.0,56.0,360.0,1.0,Rural
58,Male,Yes,1,Graduate,No,8080,2250.0,180.0,360.0,1.0,Urban
196,Male,No,0,Graduate,No,8333,3750.0,187.0,360.0,1.0,Rural
69,Female,No,0,Graduate,No,4300,0.0,136.0,360.0,0.0,Semiurban
224,Male,Yes,0,Graduate,No,6250,0.0,128.0,360.0,1.0,Semiurban
217,Male,Yes,0,Graduate,No,3727,1775.0,131.0,360.0,1.0,Semiurban
593,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural
253,Male,Yes,1,Not Graduate,No,2661,7101.0,279.0,180.0,1.0,Semiurban
200,Male,Yes,1,Not Graduate,No,2600,2500.0,90.0,360.0,1.0,Semiurban
280,Male,No,1,Not Graduate,Yes,4053,2426.0,158.0,360.0,0.0,Urban
575,Male,Yes,2,Graduate,No,3159,461.0,108.0,84.0,1.0,Urban
566,Male,No,0,Graduate,No,3333,0.0,70.0,360.0,1.0,Urban
557,Male,Yes,3+,Graduate,Yes,10139,0.0,260.0,360.0,1.0,Semiurban
510,Male,No,0,Not Graduate,No,3598,1287.0,100.0,360.0,1.0,Rural
205,Female,No,0,Not Graduate,No,4408,0.0,120.0,360.0,1.0,Semiurban
203,Male,Yes,1,Not Graduate,No,3500,1083.0,135.0,360.0,1.0,Urban
62,Male,Yes,0,Not Graduate,Yes,2609,3449.0,165.0,180.0,0.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
518,Male,No,0,Graduate,No,4683,1915.0,185.0,360.0,1.0,Semiurban
342,Male,Yes,1,Not Graduate,No,4554,1229.0,158.0,360.0,1.0,Urban
91,Male,Yes,2,Graduate,No,6250,5654.0,188.0,180.0,1.0,Semiurban
426,Female,No,1,Not Graduate,No,4606,0.0,81.0,360.0,1.0,Rural
33,Male,Yes,0,Graduate,No,3500,1667.0,114.0,360.0,1.0,Semiurban
211,Male,Yes,3+,Graduate,No,3430,1250.0,128.0,360.0,0.0,Semiurban
430,Female,No,1,Graduate,Yes,8624,0.0,150.0,360.0,1.0,Semiurban
594,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban
222,Male,No,0,Graduate,No,2971,2791.0,144.0,360.0,1.0,Semiurban
596,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural
52,Female,No,0,Graduate,No,4230,0.0,112.0,360.0,1.0,Semiurban
248,Male,Yes,1,Graduate,No,2882,1843.0,123.0,480.0,1.0,Semiurban
404,Female,No,0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural
509,Female,No,1,Graduate,No,13262,0.0,40.0,360.0,1.0,Urban
116,Female,Yes,0,Graduate,No,3167,2283.0,154.0,360.0,1.0,Semiurban
89,Male,Yes,0,Graduate,No,5695,4167.0,175.0,360.0,1.0,Semiurban
115,Male,Yes,1,Graduate,No,14583,0.0,185.0,180.0,1.0,Rural
376,Male,Yes,3+,Graduate,No,8750,4996.0,130.0,360.0,1.0,Rural
306,Female,No,0,Graduate,No,3762,1666.0,135.0,360.0,1.0,Rural
358,Male,Yes,0,Not Graduate,No,3000,1666.0,100.0,480.0,0.0,Urban
269,Female,No,1,Graduate,No,2876,1560.0,90.0,360.0,1.0,Urban
10,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban
459,Male,Yes,0,Graduate,No,8334,0.0,160.0,360.0,1.0,Semiurban
250,Male,Yes,0,Not Graduate,No,1668,3890.0,201.0,360.0,0.0,Semiurban
320,Male,Yes,0,Graduate,No,2400,2167.0,115.0,360.0,1.0,Semiurban
414,Female,Yes,0,Not Graduate,No,2149,3237.0,178.0,360.0,0.0,Semiurban
247,Male,Yes,1,Not Graduate,No,6608,0.0,137.0,180.0,1.0,Urban
152,Male,No,0,Graduate,No,9166,0.0,244.0,360.0,1.0,Urban
60,Male,Yes,0,Graduate,No,2500,3796.0,120.0,360.0,1.0,Urban
220,Male,Yes,0,Graduate,No,2221,0.0,60.0,360.0,0.0,Urban

In [78]:
X_test

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
18,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural
161,Male,Yes,0,Graduate,No,7933,0.0,275.0,360.0,1.0,Urban
182,Male,Yes,0,Graduate,No,4600,0.0,73.0,180.0,1.0,Semiurban
340,Male,Yes,3+,Not Graduate,No,2647,1587.0,173.0,360.0,1.0,Rural
216,Male,Yes,0,Graduate,No,150,1800.0,135.0,360.0,1.0,Rural
183,Male,Yes,1,Graduate,No,33846,0.0,260.0,360.0,1.0,Semiurban
512,Male,Yes,2,Graduate,No,3283,2035.0,148.0,360.0,1.0,Urban
549,Male,Yes,0,Graduate,No,2785,2016.0,110.0,360.0,1.0,Rural
148,Female,No,0,Graduate,No,10000,1666.0,225.0,360.0,1.0,Rural
27,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban
440,Male,No,0,Graduate,No,3660,5064.0,187.0,360.0,1.0,Semiurban
153,Male,Yes,2,Not Graduate,No,2281,0.0,113.0,360.0,1.0,Rural
564,Male,Yes,2,Graduate,No,8799,0.0,258.0,360.0,0.0,Urban
418,Male,Yes,0,Graduate,No,1025,2773.0,112.0,360.0,1.0,Rural
319,Male,Yes,1,Graduate,Yes,10000,0.0,155.0,360.0,1.0,Rural
285,Male,No,0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural
94,Male,No,0,Not Graduate,No,3620,0.0,25.0,120.0,1.0,Semiurban
137,Male,Yes,2,Graduate,Yes,3316,3500.0,88.0,360.0,1.0,Urban
400,Male,Yes,2,Not Graduate,No,2889,0.0,45.0,180.0,0.0,Urban
455,Male,Yes,2,Graduate,No,3859,0.0,96.0,360.0,1.0,Semiurban
599,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban
135,Male,Yes,3+,Graduate,No,4000,7750.0,290.0,360.0,1.0,Semiurban
310,Female,No,0,Graduate,No,2917,0.0,84.0,360.0,1.0,Semiurban
50,Female,Yes,0,Not Graduate,No,1928,1644.0,100.0,360.0,1.0,Semiurban
500,Female,No,0,Graduate,No,645,3683.0,113.0,480.0,1.0,Rural
409,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural
277,Male,Yes,0,Graduate,No,3103,1300.0,80.0,360.0,1.0,Urban
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural
558,Male,Yes,0,Graduate,No,3887,2669.0,162.0,360.0,1.0,Semiurban
445,Male,Yes,1,Graduate,Yes,3466,1210.0,130.0,360.0,1.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
401,Male,No,0,Not Graduate,No,2755,0.0,65.0,300.0,1.0,Rural
96,Female,Yes,0,Graduate,No,2484,2302.0,137.0,360.0,1.0,Semiurban
520,Male,Yes,2,Not Graduate,No,2192,1742.0,45.0,360.0,1.0,Semiurban
424,Male,Yes,0,Graduate,No,14880,0.0,96.0,360.0,1.0,Semiurban
185,Male,Yes,0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban
68,Male,Yes,3+,Not Graduate,Yes,7100,0.0,125.0,60.0,1.0,Urban
607,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural
291,Male,Yes,2,Graduate,No,4400,0.0,127.0,360.0,0.0,Semiurban
311,Male,No,0,Not Graduate,No,2927,2405.0,111.0,360.0,1.0,Semiurban
386,Male,No,0,Not Graduate,No,2346,1600.0,132.0,360.0,1.0,Semiurban
606,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban
70,Male,Yes,0,Graduate,No,3208,3066.0,172.0,360.0,1.0,Urban
210,Female,No,0,Graduate,No,10000,0.0,214.0,360.0,1.0,Semiurban
75,Male,No,0,Graduate,No,3750,0.0,113.0,480.0,1.0,Urban
241,Male,Yes,1,Not Graduate,No,2510,1983.0,140.0,180.0,1.0,Urban
90,Male,Yes,0,Graduate,No,2958,2900.0,131.0,360.0,1.0,Semiurban
474,Male,No,2,Graduate,No,5532,4648.0,162.0,360.0,1.0,Rural
7,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban
119,Female,No,0,Graduate,No,10408,0.0,259.0,360.0,1.0,Urban
519,Female,No,0,Not Graduate,No,3400,0.0,95.0,360.0,1.0,Rural
300,Male,Yes,0,Not Graduate,No,1800,2934.0,93.0,360.0,0.0,Urban
362,Male,Yes,0,Graduate,No,4750,2333.0,130.0,360.0,1.0,Urban
8,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban
464,Male,No,0,Graduate,No,4166,0.0,98.0,360.0,0.0,Semiurban
9,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban
532,Male,No,2,Graduate,No,3588,0.0,110.0,360.0,0.0,Rural
534,Female,No,0,Not Graduate,Yes,18165,0.0,125.0,360.0,1.0,Urban
142,Male,No,0,Graduate,Yes,6950,0.0,175.0,180.0,1.0,Semiurban
591,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban
243,Male,Yes,2,Graduate,Yes,6250,1300.0,108.0,360.0,1.0,Rural

In [82]:
#X_train = pd.get_dummies(X_train)
#X_test  = pd.get_dummies(X_test)

print('shape of training data : ',X_train.shape)
print('shape of testing data : ',X_test.shape)

# create the object of the model
model = LogisticRegression()

model.fit(X_train,y_train)

predict = model.predict(X_test)

print('Predicted Values on Test Data',predict)

print('\n\nAccuracy Score on test data : \n\n')
print(accuracy_score(y_test,predict))

shape of training data :  (384, 20)
shape of testing data :  (96, 20)
Predicted Values on Test Data [1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1]


Accuracy Score on test data :


0.760416666667